/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Address from '../generated-artifacts/Address.json';
import * as EcIP1Mapper from '../generated-artifacts/EcIP1Mapper.json';
import * as EcIP1Proxy from '../generated-artifacts/EcIP1Proxy.json';
import * as IOwnable from '../generated-artifacts/IOwnable.json';
import * as LibBytes from '../generated-artifacts/LibBytes.json';
import * as Ownable from '../generated-artifacts/Ownable.json';
import * as ReentrancyGuard from '../generated-artifacts/ReentrancyGuard.json';
import * as SafeMath from '../generated-artifacts/SafeMath.json';
import * as TestConstants from '../generated-artifacts/TestConstants.json';
import * as TestLibAddressArray from '../generated-artifacts/TestLibAddressArray.json';
import * as TestLibBytes from '../generated-artifacts/TestLibBytes.json';
export const artifacts = {
    Address: Address as ContractArtifact,
    LibBytes: LibBytes as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    ReentrancyGuard: ReentrancyGuard as ContractArtifact,
    SafeMath: SafeMath as ContractArtifact,
    EcIP1Proxy: EcIP1Proxy as ContractArtifact,
    IOwnable: IOwnable as ContractArtifact,
    TestConstants: TestConstants as ContractArtifact,
    TestLibAddressArray: TestLibAddressArray as ContractArtifact,
    TestLibBytes: TestLibBytes as ContractArtifact,
    EcIP1Mapper: EcIP1Mapper as ContractArtifact,
};
